createLine('John', 'NAME', 'LAST')
createLine("Well, one can't have everything", 'TEXT', 'LAST')
createLine('Cut to:', 'CUT', 'LAST')
createLine("Ext. John and Mary's house - continuous", 'LOCATION', 'LAST')
createLine("An old car pulls up to the curb and a few KNOCKS as the engine shuts down.", 'ACTION', 'LAST')
createLine("MIKE steps out of the car and walks up to the front door. He rings the doorbell.", 'ACTION', 'LAST')
createLine("Back to:", 'CUT', 'LAST')
createLine("Int. Kitchen - continuous", 'LOCATION', 'LAST')
createLine("John", "NAME", "LAST")
createLine("Who on Earth could that be?", "TEXT", "LAST")
createLine("Mary", "NAME", "LAST")
createLine("I'll go and see.", "TEXT", "LAST")
createLine("Mary gets up and walks out.", "ACTION", "LAST")
createLine("The front door lock CLICKS and door CREAKS a little as it's opened.", "ACTION", "LAST")
createLine("Mary (O.S.) (CONT'D)", "NAME", "LAST")
createLine("Wel hello Mike! Come on in! John, Mike's here!", "TEXT", "LAST")
createLine("John", "NAME", "LAST")
createLine("Hiya Mike! What brings you here?", "TEXT", "LAST")
createLine("Mary walks in, Mike following. Both sit down at the kitchen table, opposite one another", "ACTION", "LAST")
createLine("Mike", "NAME", "LAST")
createLine("Oh, just thought I'd bring back your revolver. Thanks for letting me borrow it last week.", "TEXT", "LAST")
createLine("Mike reaches in his pocket and fishes out a hamerless Smith & Wesson. He opens the cylinder with a CLICK and confirms it's unloaded before setting it on the table", "ACTION", "LAST")
createLine("John removes the paper towel from his plate, setting the back down on it. Then he takes his sunny-side up eggs from the frying pan and puts them on the plate. He sits downbetween Mike and Mary.", "ACTION", "LAST")

render()